appName:  backend
namespace: groupe4
image:
  repository: registry.gitlab.com/abbaoui-ariri-elaba/colyseus-starter/backend
  tag: 1.0.0
service:
  port: 80
replicaCount: 1
containerPort: 2567

host: back.team4.rozvictor.fr